[tool.poetry]
name = "app_manager"
version = "0.1.0"
description = "App Manager SDK for Cypherock X1"
authors = ["Temiloluwa Yusuf <ytemiloluwa@gmail.com>"]
readme = "README.md"
packages = [{include = "src/app_manager"}]

[tool.poetry.dependencies]
python = ">=3.11"
betterproto = "^1.2.5"
httpx = "^0.24.0"
interfaces = {path = "../interfaces", develop = true}
util = {path = "../util", develop = true}
core = {path = "../core", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-asyncio = "^1.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
